# Generated by Django 4.1.7 on 2023-03-03 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('bronze', models.BooleanField(default=False)),
                ('silver', models.BooleanField(default=False)),
                ('gold', models.BooleanField(default=False)),
                ('platinum', models.BooleanField(default=False)),
                ('pay_as_you_go', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('plan_id', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_ref', models.CharField(max_length=50)),
                ('payment_start', models.DateTimeField(null=True)),
                ('payment_end', models.DateTimeField(null=True)),
                ('extra_gateway_values', models.TextField(default='{}', max_length=100)),
                ('renewal_enabled', models.BooleanField(default=True)),
                ('amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'pending'), ('ACTIVE', 'active'), ('FAILED', 'failed'), ('PAUSED', 'paused')], max_length=20, null=True)),
                ('subscription_start', models.DateTimeField(null=True)),
                ('subscription_end', models.DateTimeField(null=True)),
                ('renewed', models.BooleanField(default=False)),
                ('base_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor', to='payment.subscriptionpayment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.subscriptionplan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecurringSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_ref', models.CharField(max_length=60)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_subscriptions', to='payment.subscriptionpayment')),
            ],
            options={
                'ordering': ('-start',),
            },
        ),
    ]
