# Generated by Django 4.1.7 on 2023-03-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
